"""
Static compliance rules for ReguMap jurisdictions.

Each key is a regulatory_class string that maps to a rule dict with:
  badge         — PASS | FLAG | BLOCK
  regulation    — short citation label shown in UI
  clause        — full regulatory clause text
  citation      — bibliographic reference
  citation_url  — canonical URL for the regulation
  warning       — human-readable alert string, or None
"""

RULES: dict[str, dict] = {
    # ── India ─────────────────────────────────────────────────────────────────
    "IND": {
        "badge": "PASS",
        "regulation": "CDSCO Schedule M · WHO-GDP Annex 9",
        "clause": (
            "All pharmaceutical products exported from India must comply with "
            "Schedule M of the Drugs and Cosmetics Act (D&C Rules 71–76), "
            "ensuring Good Manufacturing Practices (GMP) for storage, handling, "
            "and dispatch. Cold-chain vaccines and biologics additionally require "
            "WHO Technical Report Series 908 Annex 9 temperature-mapping "
            "documentation and continuous electronic temperature logging during "
            "storage and loading. The exporter must furnish a Form 37 export "
            "declaration and a Certificate of Pharmaceutical Product (CoPP) "
            "issued by CDSCO prior to shipment departure."
        ),
        "citation": "CDSCO Schedule M (D&C Rules 1945, Amended 2005); WHO TRS 908 Annex 9",
        "citation_url": "https://cdsco.gov.in/opencms/opencms/en/Drugs/ScheduleM/",
        "warning": None,
    },

    # ── International Waters ───────────────────────────────────────────────────
    "INTL_WATERS": {
        "badge": "PASS",
        "regulation": "IMO MARPOL Annex II · WHO TRS 961",
        "clause": (
            "Pharmaceutical cargo transported through international waters must "
            "comply with IMO MARPOL 73/78 Annex II regulations governing noxious "
            "liquid substances and refrigerated cargo handling aboard vessels. "
            "Vessels must maintain an updated Cargo Record Book (CRB) and ensure "
            "cold-chain continuity per WHO Technical Report Series 961 for "
            "temperature-sensitive biological products. Continuous temperature "
            "excursion logs must be generated by a calibrated data-logger and "
            "made available for inspection at each subsequent port of call."
        ),
        "citation": "IMO MARPOL 73/78 Annex II; WHO TRS 961 (2011)",
        "citation_url": "https://www.imo.org/en/OurWork/Environment/Pages/MARPOL.aspx",
        "warning": None,
    },

    # ── Egypt — Suez Canal ────────────────────────────────────────────────────
    "EGYPT_SUEZ": {
        "badge": "FLAG",
        "regulation": "Egyptian Drug Authority Resolution 442",
        "clause": (
            "Pharmaceutical shipments transiting the Suez Canal must submit a "
            "pre-notification to the Egyptian Drug Authority (EDA) no less than "
            "72 hours prior to Canal entry, pursuant to EDA Resolution 442 "
            "Article 9. The notification package must include a full cargo "
            "manifest, cold-chain compliance certificates, shipper and consignee "
            "details, and an emergency contact registered with the EDA. Failure "
            "to notify within the prescribed window may result in mandatory "
            "diversion to Port Said anchorage for physical inspection, delaying "
            "transit by 24–96 hours. Emergency pharmaceutical consignments "
            "qualifying under WHO Prequalification may apply for expedited "
            "clearance through the EDA Port Said Liaison Office (Article 12)."
        ),
        "citation": "EDA Resolution 442, Article 9 (2019); Egyptian Customs Law 207/2020",
        "citation_url": "https://www.eda.mohp.gov.eg/",
        "warning": (
            "\u26a0 72-hour pre-notification \u00b7 EDA Article 9 "
            "\u00b7 Emergency staging: Port Said"
        ),
    },

    # ── United States ─────────────────────────────────────────────────────────
    "USA": {
        "badge": "PASS",
        "regulation": "FDA 21 CFR Part 211 \u00b7 USP \u003c1079\u003e",
        "clause": (
            "Imported pharmaceutical products must comply with FDA 21 CFR "
            "Part 211 (Current Good Manufacturing Practice for Finished "
            "Pharmaceuticals) and USP General Chapter <1079> (Good Storage and "
            "Distribution Practices for Drug Products). Importers must file FDA "
            "Prior Notice of Imported Drug Shipments through PREDICT/OASIS at "
            "least 8 hours before arrival by sea. Vaccines and biologics "
            "additionally require a valid FDA Biologics License Application "
            "(BLA) and CBER lot-release authorization for each imported batch. "
            "Cold-chain documentation—including calibrated min/max temperature "
            "logs and mean kinetic temperature (MKT) calculations—must accompany "
            "the shipment and be presented to FDA at the port of entry."
        ),
        "citation": "21 CFR Part 211; USP <1079>; FDA Guidance for Industry: Imported Drug Products",
        "citation_url": (
            "https://www.fda.gov/drugs/pharmaceutical-quality-resources/"
            "current-good-manufacturing-practice-regulations"
        ),
        "warning": None,
    },
}
